[package]
name = "dih"
version = "0.1.0"
authors = ["Oleksandr Litus <oleks.litus@gmail.com>"]
edition = "2018"

[[bin]]
name = "dih"

[dependencies]
regex = "1"
colored = "2"
Inflector = "0.11.4"
rayon = "1.5"
indicatif = {version = "*", features = ["rayon"]}