[package]
name = "dih"
version = "0.1.0"
authors = ["Oleksandr Litus <oleks.litus@gmail.com>"]
edition = "2018"

[[bin]]
name = "dih"

[dependencies]
regex = "1"
clap = "~2.27.0"
colored = "2"
Inflector = "0.11.4"